from django.urls import path
from Backend import views

urlpatterns=[path('admin_home/', views.admin_home, name='admin_home'),
             path('login_reg/', views.login_reg, name='login_reg'),
             path('signup/', views.signup, name='signup'),
             path('admin_login/', views.admin_login, name='admin_login'),
             path('admin_logout/', views.admin_logout, name='admin_logout'),
             path('admin_profile/', views.admin_profile, name='admin_profile'),
             path('update_user/<int:dataid>/', views.update_user, name="update_user"),
             path('change_password/', views.change_password, name='change_password'),
             path('update_password/', views.update_password, name='update_password'),
             path('add_admin/', views.add_admin, name='add_admin'),
             path('list_admin/', views.list_admin, name='list_admin'),
             path('submit_admin/', views.submit_admin, name='submit_admin'),
             path('edit_admin/<int:dataid>/', views.edit_admin, name='edit_admin'),
             path('delete_admin/<int:dataid>/', views.delete_admin, name='delete_admin'),
             path('change_password_admin/<int:dataid>/', views.change_password_admin, name='change_password_admin'),
             path('update_password_admin/<int:dataid>/', views.update_password_admin, name='update_password_admin'),
             path('theatre_details/', views.theatre_details, name='theatre_details'),
             path('edit_theatre/<int:dataid>/', views.edit_theatre, name='edit_theatre'),
             path('update_theatre/<int:dataid>/', views.update_theatre, name='update_theatre'),
             path('add_screen/', views.add_screen, name='add_screen'),
             path('list_screen/', views.list_screen, name='list_screen'),
             path('submit_screen/', views.submit_screen, name='submit_screen'),
             path('edit_screen/<int:dataid>/', views.edit_screen, name='edit_screen'),
             path('update_screen/<int:dataid>/', views.update_screen, name='update_screen'),
            path('delete_screen/<int:dataid>/', views.delete_screen, name='delete_screen'),
             path('add_movie/', views.add_movie, name='add_movie'),
             path('submit_movie/', views.submit_movie, name='submit_movie'),
             path('list_movie/', views.list_movie, name='list_movie'),
             path('edit_movie/<int:dataid>/', views.edit_movie, name='edit_movie'),
             path('update_movie/<int:dataid>/', views.update_movie, name='update_movie'),
             path('delete_movie/<int:dataid>/', views.delete_movie, name='delete_movie'),
             path('add_show_time/', views.add_show_time, name='add_show_time'),
             path('submit_show_time/', views.submit_show_time, name='submit_show_time'),
             path('list_showtime/', views.list_showtime, name='list_showtime'),
             path('edit_showtime/<int:dataid>/', views.edit_showtime, name='edit_showtime'),
             path('delete_showtime/<int:dataid>/', views.delete_showtime, name='delete_showtime'),
             path('update_show_time/<int:dataid>/', views.update_show_time, name='update_show_time'),
             path('submit_movie/', views.submit_movie, name='submit_movie'),
             path('view_messages/', views.view_messages, name='view_messages'),
             path('view_bookings/', views.view_bookings, name='view_bookings'),
             path('view_bookings_old/', views.view_bookings_old, name='view_bookings_old'),
             path('view_users/', views.view_users, name='view_users'),


             ]