# Generated by Django 3.2.10 on 2023-08-05 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0003_screendb'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActorDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ActorName', models.CharField(blank=True, max_length=200, null=True)),
                ('ActorImage', models.ImageField(blank=True, null=True, upload_to='ActorImages')),
            ],
        ),
        migrations.CreateModel(
            name='CrewDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CrewName', models.CharField(blank=True, max_length=200, null=True)),
                ('CrewRole', models.CharField(blank=True, max_length=200, null=True)),
                ('CrewImage', models.ImageField(blank=True, null=True, upload_to='ActorImages')),
            ],
        ),
        migrations.CreateModel(
            name='MovieDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MovieName', models.CharField(blank=True, max_length=200, null=True)),
                ('MovieLanguage', models.CharField(blank=True, max_length=200, null=True)),
                ('MovieGenre', models.CharField(blank=True, max_length=200, null=True)),
                ('MoviePoster', models.ImageField(blank=True, null=True, upload_to='MoviePoster')),
                ('MovieType', models.CharField(blank=True, max_length=2, null=True)),
                ('MovieSynopsis', models.CharField(blank=True, max_length=500, null=True)),
                ('MovieDuration', models.CharField(blank=True, max_length=10, null=True)),
                ('MovieRelease', models.CharField(blank=True, max_length=10, null=True)),
                ('MovieActor', models.ManyToManyField(to='Backend.ActorDB')),
                ('MovieCrew', models.ManyToManyField(to='Backend.CrewDB')),
            ],
        ),
    ]
