# Generated by Django 3.2.10 on 2023-08-05 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0005_auto_20230805_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedb',
            name='MovieRelease',
            field=models.DateField(blank=True, max_length=10, null=True),
        ),
    ]
