# Generated by Django 3.2.10 on 2023-08-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0006_alter_moviedb_movierelease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedb',
            name='MovieCrew1Image',
            field=models.ImageField(blank=True, null=True, upload_to='Crew'),
        ),
        migrations.AlterField(
            model_name='moviedb',
            name='MovieCrew3Image',
            field=models.ImageField(blank=True, null=True, upload_to='Crew'),
        ),
        migrations.AlterField(
            model_name='moviedb',
            name='MovieCrew4Image',
            field=models.ImageField(blank=True, null=True, upload_to='Crew'),
        ),
        migrations.AlterField(
            model_name='moviedb',
            name='MovieCrew5Image',
            field=models.ImageField(blank=True, null=True, upload_to='Crew'),
        ),
    ]
