# Generated by Django 3.2.10 on 2023-08-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0007_auto_20230805_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedb',
            name='MovieCrew2Image',
            field=models.ImageField(blank=True, null=True, upload_to='Crew'),
        ),
    ]
