# Generated by Django 3.2.10 on 2023-08-07 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0008_moviedb_moviecrew2image'),
    ]

    operations = [
        migrations.AddField(
            model_name='screendb',
            name='ScreenStatus',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
