# Generated by Django 3.2.10 on 2023-08-07 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0009_screendb_screenstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowTimeDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MovieName', models.CharField(blank=True, max_length=200, null=True)),
                ('ScreenName', models.CharField(blank=True, max_length=200, null=True)),
                ('StartTime', models.TimeField(blank=True, null=True)),
                ('EndTime', models.TimeField(blank=True, null=True)),
                ('Date', models.DateField(blank=True, null=True)),
                ('PriceStandard', models.IntegerField(blank=True, null=True)),
                ('PricePremium', models.IntegerField(blank=True, null=True)),
                ('Status', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
