# Generated by Django 3.2.10 on 2023-08-07 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0010_showtimedb'),
    ]

    operations = [
        migrations.AddField(
            model_name='showtimedb',
            name='AvailablePremiumTickets',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='showtimedb',
            name='AvailableStandardTickets',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='showtimedb',
            name='TotalPremiumTickets',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='showtimedb',
            name='TotalStandardTickets',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
