# Generated by Django 3.2.10 on 2023-08-12 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0013_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedb',
            name='MovieStatus',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
