# Generated by Django 3.2.10 on 2023-08-12 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0014_moviedb_moviestatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showtimedb',
            name='EndTime',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='showtimedb',
            name='StartTime',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
