# Generated by Django 3.2.10 on 2023-08-12 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0015_auto_20230812_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='showtimedb',
            name='ShowTimeName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
