# Generated by Django 3.2.10 on 2023-08-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0016_showtimedb_showtimename'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatingDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ShowTimeName', models.CharField(blank=True, max_length=200, null=True)),
                ('SeatClass', models.CharField(blank=True, max_length=200, null=True)),
                ('SeatNumber', models.CharField(blank=True, max_length=5, null=True)),
                ('Status', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
