# Generated by Django 3.2.10 on 2023-08-12 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0019_remove_screendb_seatavail'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatingdb',
            name='ScreenName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
