# Generated by Django 3.2.10 on 2023-08-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0020_seatingdb_screenname'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedb',
            name='MoviePoster1',
            field=models.ImageField(blank=True, null=True, upload_to='MoviePoster'),
        ),
    ]
