# Generated by Django 3.2.10 on 2023-08-16 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0021_moviedb_movieposter1'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedb',
            name='MovieTrailer',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
