# Generated by Django 3.2.10 on 2023-08-22 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0024_alter_moviedb_movieposter1'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedb',
            name='MoviePoster2',
            field=models.ImageField(blank=True, null=True, upload_to='MoviePoster'),
        ),
        migrations.AddField(
            model_name='moviedb',
            name='MoviePoster3',
            field=models.ImageField(blank=True, null=True, upload_to='MoviePoster'),
        ),
    ]
