# Generated by Django 3.2.10 on 2023-08-16 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdb',
            name='UserName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
