# Generated by Django 3.2.10 on 2023-08-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0002_userdb_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(blank=True, max_length=100, null=True)),
                ('Review', models.CharField(blank=True, max_length=500, null=True)),
                ('Date', models.DateField(blank=True, null=True)),
                ('MovieName', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
