# Generated by Django 3.2.10 on 2023-08-18 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0006_seat'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SeatNumber', models.CharField(max_length=5)),
                ('SeatStatus', models.CharField(max_length=20)),
                ('Date', models.DateField()),
                ('ShowName', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Seat',
        ),
    ]
