# Generated by Django 3.2.10 on 2023-08-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0008_rename_showname_seatdb_showtimename'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatdb',
            name='SeatType',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
