# Generated by Django 3.2.10 on 2023-08-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0009_seatdb_seattype'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatdb',
            name='RowNumber',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
