# Generated by Django 3.2.10 on 2023-08-21 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0010_seatdb_rownumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbookingdb',
            name='SeatType',
        ),
    ]
