# Generated by Django 3.2.10 on 2023-08-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0011_remove_userbookingdb_seattype'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbookingdb',
            name='AmountToBePaid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
