# Generated by Django 3.2.10 on 2023-08-21 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0012_userbookingdb_amounttobepaid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbookingdb',
            name='StartTime',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
