# Generated by Django 3.2.10 on 2023-08-22 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0014_userbookingdb_seatnumberonly'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdb',
            name='UserAddress',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userdb',
            name='UserFirstName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userdb',
            name='UserImage',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images'),
        ),
        migrations.AddField(
            model_name='userdb',
            name='UserLastName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
