# Generated by Django 3.2.10 on 2023-08-23 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0015_auto_20230822_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewdb',
            name='UserImage',
            field=models.ImageField(blank=True, null=True, upload_to='profileImage'),
        ),
    ]
