# Generated by Django 3.2.10 on 2023-09-11 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0017_alter_userdb_userimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbookingdb',
            name='SeatImage',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
