# Generated by Django 3.2.10 on 2023-09-11 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0018_userbookingdb_seatimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbookingdb',
            name='SeatImage',
        ),
    ]
