# Generated by Django 3.2.10 on 2023-09-11 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0019_remove_userbookingdb_seatimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckOutDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(blank=True, max_length=20, null=True)),
                ('Email', models.EmailField(blank=True, max_length=20, null=True)),
                ('Contact', models.IntegerField(blank=True, null=True)),
                ('CardName', models.CharField(blank=True, max_length=20, null=True)),
                ('Expiry', models.IntegerField(blank=True, null=True)),
                ('Cvv', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
