# Generated by Django 3.2.10 on 2023-09-11 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0020_checkoutdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutdb',
            name='CardDetail',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
