# Generated by Django 3.2.10 on 2023-09-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0022_auto_20230917_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbookingdb',
            name='OrderId',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userbookingdb',
            name='TransactionId',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
